services:
  postgres:
    container_name: infirmary_db_container
    build:
      context: ./DB
      dockerfile: Dockerfile.postgres
    restart: always
    env_file:
      - DB/secrets.env
    volumes:
      - ./DB/pgData:/var/lib/postgresql/data
    networks:
     - devbridge
  backend:
   container_name: infirmary_backend_container
   build:
     context: ./backend
     dockerfile: Dockerfile
   ports:
     - 8081:8081
   networks:
     - devbridge
   env_file:
     - backend/secrets.env

networks:
 devbridge: