version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: infirmary_db_container
    restart: always
    env_file:
      - DB/secrets.env
    volumes:
      - ./DB/migrations:/docker-entrypoint-initdb.d/init.sql
      - ./DB/pgData:/var/lib/postgresql/data
    ports:
      - 5432:5432
#     networks:
#      - devbridge
#   backend:
#    container_name: infirmary_backend_container
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    ports:
#      - 8081:8081
#    networks:
#      - devbridge
#    env_file:
#      - backend/secrets.env

# networks:
#  devbridge: